### ISSUE TITLE
Error occured after command: "docker-compose up"

### ISSUE THREAD

**Issue by fish1968** [primihub/primihub#1]
The error messages are listed below:
_ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/_

**Comment by hobo0cn** [comment]
Yes, it's a issue, thx.

**Comment by hobo0cn** [comment]
In fact the latest docker also supports 3.9.  See: here https://github.com/docker/cli/pull/2073/commits/5bc1f24dfd9f0071f7b857658c38226b695a0997. 
Anyway I will follow docker compose docs.

**Comment by fish1968** [comment]
> Thanks for ur replay! In fact, this is my very first time using docker, hopefully it's not my problem. Wish it will work well soon. Many thanks!

**Comment by hobo0cn** [comment]
Fix in [this pull request](https://github.com/primihub/primihub/pull/3/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3)
I'll close this issue.
