### ISSUE TITLE
node connect failed

### ISSUE THREAD

**Issue by lijrhw** [primihub/primihub#120]
We have already deployed the nodes on the different devices and make sure the ports that we need is open and vaild.But the nodes seems can not communicate with each other.Please help,Thank you.

**Comment by lijrhw** [comment]
[error .txt](https://github.com/primihub/primihub/files/9531906/error.txt)

**Comment by hobo0cn** [comment]
No response？I'll close this issue. Welcome submit any issue @lijrhw .
