### ISSUE TITLE
Request to have a development guide

### ISSUE THREAD

**Issue by LinuxSuRen** [primihub/primihub#149]
Please consider adding the following basic content:

* How to set up a development environment?
* How to compile this project?
* Which branch should we use when creating a PR?
* If we have a code style guide?
* others

**Comment by phoenix20162016** [comment]
1) https://docs.primihub.com/docs/core-concept/model
following this doc, you can reimplement the function which can meet your demands
2) to comiple primihub node, you just using make command and specifiy the platform what you need, such as:
TARGET := //:node \
         //:cli \
         //src/primihub/pybind_warpper:linkcontext \
         //src/primihub/pybind_warpper:opt_paillier_c2py \
         //:py_main
linux_aarch64:
	bazel build --config=linux_aarch64 ${TARGET}
3) if you find bug during using primihub service, you are highly welcome to create PR to help us fix it, what you just do is fork primihub repo, and then fix the problem based on develop branch, and then create a pull request to our develop, specifiy a reviewer,   if the  CICD is passed, we will merger your PR as soon as possible,  and finally thanks for your contribute.
