### ISSUE TITLE
Failed to run Python SDK due to No module named 'opt_paillier_c2py'

### ISSUE THREAD

**Issue by LinuxSuRen** [primihub/primihub#168]
I followed the instructions from [this document](https://docs.primihub.com/docs/advance-usage/fedreated-learning/xgb). But I still got the following error message:

```shell
vscode ➜ /workspaces/primihub/python (develop ✗) $ python primihub/tests/test_disxgb_en.py
Traceback (most recent call last):
  File "/workspaces/primihub/python/primihub/tests/test_disxgb_en.py", line 25, in <module>
    from primihub.examples.disxgb_en import xgb_host_logic, xgb_guest_logic
  File "/workspaces/primihub/python/primihub/examples/disxgb_en.py", line 20, in <module>
    from primihub.primitive.opt_paillier_c2py_warpper import *
  File "/workspaces/primihub/python/primihub/primitive/opt_paillier_c2py_warpper.py", line 1, in <module>
    import opt_paillier_c2py
ModuleNotFoundError: No module named 'opt_paillier_c2py'
```

**Comment by lzw9560** [comment]
Sorry, the documentation you see has timed out.
If you want to execute this test case, complete the following steps:
1. Compile opt_paillier_c2py, see: [Developer-docs](url)
2. Install Primihub package: see: [Python SDK Insell](https://docs.primihub.com/docs/advance-usage/python-sdk/install)
3. Run: `python primihub/tests/test_disxgb_en.py`

We will update the documentation as soon as possible, thk you.
