### ISSUE TITLE
Unable to run node

### ISSUE THREAD

**Issue by Rui-learning** [primihub/primihub#17]
There is no error in the process of compiling the code, but an error is reported when running the node, as shown below:
![image](https://user-images.githubusercontent.com/55970946/174744775-ac988d70-68cf-434b-a0e8-ae6a7c594947.png)

**Comment by Rui-learning** [comment]
![image](https://user-images.githubusercontent.com/55970946/174745294-414c55a8-c812-4ffa-92d8-30ad734fc63c.png)

**Comment by hobo0cn** [comment]
In source code root path, run this:
```
./bazel-bin/node  --node_id=node0 --service_port=50050 --config=./config/node0.yaml
```
I‘ll correct it on the developer documentation.

**Comment by Rui-learning** [comment]
thanks，but I have this problem again：
![image](https://user-images.githubusercontent.com/55970946/174756761-3830a930-f367-4b38-bfbd-f360c8527584.png)

**Comment by hobo0cn** [comment]
Generate test data first, run this:
```
 cd test/primihub/script
sudo bash ./gen_logistic_data.sh
```

**Comment by Rui-learning** [comment]
But when I run this command, there will be a connection refused error, is it a network problem?
![image](https://user-images.githubusercontent.com/55970946/174792235-d32af7f3-9631-4309-9456-636663c2c077.png)

**Comment by zjning95** [comment]
In source code root path, run this:
`cp ./data/* /tmp/`

**Comment by Rui-learning** [comment]
This method does not work either, and my virtual machine network should be fine.
run `ping www.baidu.com`is allowed

**Comment by Rui-learning** [comment]
At the same time, after I start the node with the data in `/data`, I don't know how to complete an MPC calculation, can you guide me?

**Comment by zjning95** [comment]
run default task
`./bazel-bin/cli`

**Comment by Rui-learning** [comment]
运行默认任务之后，得到了这样的结果，是我的参数设置有问题嘛？
![image](https://user-images.githubusercontent.com/55970946/174799264-0f5f22a0-0463-47cd-843b-b29d06bb59db.png)

**Comment by zjning95** [comment]
1.https://docs.primihub.com/docs/advance-usage/start-nodes 启动点的项目目前有正确运行吗？本机有没有4001端口？
2.`./bazel-bin/cli` 运行后有没有正常退出，像这样的输出
`# ./bazel-bin/cli --server="192.168.99.20:9051"
Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20220621-173349.75816!I20220621 17:33:49.151315 75816 cli.cc:172] SDK SubmitTask to: 127.0.0.1:50050
I20220621 17:33:49.153991 75816 cli.cc:130]  SubmitTask...
I20220621 17:34:03.793741 75816 cli.cc:135] SubmitTask rpc succeeded.
I20220621 17:34:03.793792 75816 cli.cc:137] job_id: 100 success
`
3.node1和node2节点有没有这样的日志
![image](https://user-images.githubusercontent.com/26339492/174801714-0e46b870-cfa0-41a1-a837-fd5551a4bb01.png)

**Comment by zjning95** [comment]
*2.
![image](https://user-images.githubusercontent.com/26339492/174802116-1690b9bb-17f2-4138-ba29-ac2f66404117.png)

**Comment by Rui-learning** [comment]
我的启动节点没有运行，这个问题是go的版本不对么？
![image](https://user-images.githubusercontent.com/55970946/174804657-39178f34-b603-4056-b893-d0712be6a444.png)

**Comment by hobo0cn** [comment]
Communicate in English PLEASE. Primihub is distributed globally.

**Comment by Rui-learning** [comment]
I replaced go1.18, but there is still a connection refused error when running。
![image](https://user-images.githubusercontent.com/55970946/174831824-74fa4baf-ba62-4842-9626-820e09f44b3d.png)

**Comment by Rui-learning** [comment]
thank you

**Comment by hobo0cn** [comment]
Already correct online document, I'll close this issue.
