### ISSUE TITLE
Suggestion: release the Python SDK to the PyPI service 

### ISSUE THREAD

**Issue by LinuxSuRen** [primihub/primihub#174]
## Background
Currently, it's pretty complex if someone wants to try the Python SDK. Usually, people might need. to handle many environment or version issues when they try to compile the source code. It might take 30 minutes or even more time during this process.

## Suggestion
[PyPI](https://pypi.org/) is a very popular python library center service. I highly recommend releasing [the Python SDK](https://github.com/primihub/primihub/tree/develop/python) there. Users will don't need to care about how to compile the Python SDK anymore.

I did some work on that. It should not be hard work. Please see also [this tutorial](https://towardsdatascience.com/how-to-upload-your-python-package-to-pypi-de1b363a1b3)

**Comment by phoenix20162016** [comment]
it is really a gool idear to make the sdk as pypi package, but  the python SDK is not ease as what we think, cause, some function is a wrapper to cpp code, so it is dependens on the operation system. 
if you just want to use python sdk only, it is not necessary to compile all  target, just compile the python deps only.
