### ISSUE TITLE
Suggestion: provide a roadmap for this project

### ISSUE THREAD

**Issue by LinuxSuRen** [primihub/primihub#175]
A clear roadmap is very important for an open-source community. Users or contributors could know the long-term plan of the community. Even better, people might have a chance to collaborate with the community on some new features.

In order to make our life easier. I have listed some examples:

* https://argo-cd.readthedocs.io/en/stable/roadmap/
* https://github.com/kubernetes/kubernetes/#roadmap
* https://github.com/tektoncd/pipeline/blob/main/roadmap.md
* https://fluxcd.io/roadmap/

**Comment by phoenix20162016** [comment]
https://github.com/orgs/primihub/projects/3

the roadmap will update periodically
