### ISSUE TITLE
PIR and PSI operational issues

### ISSUE THREAD

**Issue by lvrui-code** [primihub/primihub#19]
I run the default task is success，but When I running MPC, PSI and PIR tasks according to the document, the following error is reported. How should the command be modified?

default task：
![image](https://user-images.githubusercontent.com/55970946/174979355-162e6064-72f3-45a9-bdd2-a21aad0136d5.png)

MPC task：
![image](https://user-images.githubusercontent.com/55970946/174979430-2d00938e-c957-4a0a-b138-a526275d2e5f.png)

PSI task：
 
![image](https://user-images.githubusercontent.com/55970946/174979527-74757817-20a2-4709-b3d5-df141ae5fa8e.png)

PIR task：
![image](https://user-images.githubusercontent.com/55970946/174979617-f12022e0-bf96-469a-ab4b-61bba7728fd5.png)

**Comment by zjning95** [comment]
Please replace primihub-cli with ./bazel-bin/cli , and we will revise the document as soon as possible.

**Comment by Rui-learning** [comment]
This is the result of the MPC task after the replacement. What is the reason?
![Uploading image.png…]()

**Comment by zjning95** [comment]
run this
`./bazel-bin/cli --task_lang=proto --task_type=0 --task_code="logistic_regression" --params="BatchSize:INT32:0:128,NumIters:INT32:0:100,TrainData:STRING:0:train_party_0;train_party_1;train_party_2,TestData:STRING:0:test_party_0;test_party_1;test_party_2"`

**Comment by Rui-learning** [comment]
This command can be run, is the result file stored in the /tmp folder?

**Comment by Rui-learning** [comment]
How can I view the contents of the /bazel-bin/cli file?

**Comment by hobo0cn** [comment]
> This command can be run, is the result file stored in the /tmp folder?

https://github.com/primihub/primihub/blob/9c60de7f39805239c8fa2e8c6bcbcdf2ce03cb50/src/primihub/algorithm/logistic.cc#L515

**Comment by hobo0cn** [comment]
> At the same time, after the three parties complete the logistic regression training, how should the trained model be used?

After training complete, the trained data is still registered in the P2P network, waiting to be used by the next task. https://github.com/primihub/primihub/blob/9c60de7f39805239c8fa2e8c6bcbcdf2ce03cb50/src/primihub/algorithm/logistic.cc#L526

**Comment by hobo0cn** [comment]
> How can I view the contents of the /bazel-bin/cli file?

cli source code is [here](https://github.com/primihub/primihub/blob/master/src/primihub/cli/cli.cc)
