### ISSUE TITLE
Linux arm64下怎么编译安装

### ISSUE THREAD

**Issue by viknana** [primihub/primihub#212]
**Describe the bug**
linux arm64环境怎么编译？现在支持么

**Expected behavior**

**Log output**
If applicable, post the log output to help explain your problem.

**Enviroment (please complete the following information):**
 - OS: [Linux]
 - Arch: [arm64]
 - Version of Primihub:

**Additional context**

**Comment by fuxingbit** [comment]
由于MPC等任务使用的协议依赖Inter CPU的指令集，目前主分支不支持arm下编译，以前做适配的linux_arm_build分支可以在arm下编译，但是比现在的主分支要少很多功能，主分支我们这周测试下，但肯定是需要阉割一些功能才能在arm下使用。

**Comment by fuxingbit** [comment]
arm下编译现在已支持
`bash pre_build.sh && ARCH=`arch` && bazel build --config=linux_$ARCH :node :cli :opt_paillier_c2py :linkcontext`

**Comment by phoenix20162016** [comment]
since the issue has been solved, close this issue

**Comment by phoenix20162016** [comment]
since the issue has been solved, close this issue
