### ISSUE TITLE
Failed to Homo LR and Hetero XGB

### ISSUE THREAD

**Issue by 271983592** [primihub/primihub#224]
Hi,all
  Firstly, thanks for your job.
  I want to learn more about primihub, and followed these steps from https://docs.primihub.com/docs/category/%E8%81%94%E9%82%A6%E5%AD%A6%E4%B9%A0. Bug some issues comes with me.

Homo LR
...
I20221125 09:23:33.820232 412549 service.cc:307] Found local meta: {
    "data_type": 0,
    "data_url": "node0:127.0.0.1:50050:data/FL/wisconsin.data",
    "description": "breast_0",
    "driver_type": "CSV",
    "id": "bafkreie2sapjk7dbcb3oheynzt2kqpxq7rl7nz5c6hezailrqtomxmyjn4",
    "schema": "{\"1000025\":[],\"5\":[],\"1\":[],\"1\":[],\"1\":[],\"2\":[],\"1\":[],\"3\":[],\"1\":[],\"1\":[],\"2\":[]}",
    "visibility": 1
}
Get value request success 
Get value request success 
**E20221125 09:23:34.952518 412549 service.cc:292]  🔍 ⏱️  Timeout while searching meta list.**

Hetero XGB
...
2022-11-25 09:24:47.200 | ERROR    | primihub.context:get_task_type:95 - Task type in all role must be the same.
2022-11-25 09:24:47.200 | ERROR    | primihub.context:get_task_type:95 - Task type in all role must be the same.
E20221125 09:24:47.200563 412531 py_parser.cc:102] Failed to parse python: Unable to cast Python instance to C++ type (compile in debug mode for details)

 I look forward to your help. Thanks.

**Comment by xujiangyu** [comment]
It seems that the config file was set up wrongly. Please make sure you have checked to "develop" branch.

**Comment by 271983592** [comment]
I have tried to debug v1.5.0, and found that when trying to get meta of dataset, remote nodes "putValue" into ipfs successfully while the local node seemed to "getValue" successfully. But the result of value is null. Maybe something wrong with my config about ipfs? I have checked but unfortunately I still can't find out the problem.

**Comment by fuxingbit** [comment]
You can try to start bootstrap_node with docker
```
docker run --name bootstrap-node -d -p 4001:4001 primihub/simple-bootstrap-node:1.0
```
Then modify 127.0.0.1 in the configuration file to your host IP. You can use this command to replace globally
```
sed -ri 's/([0-9]{1,3}\.){3}[0-9]{1,3}/YOUR_HOST_IP/g' config/node*
```

**Comment by fuxingbit** [comment]
We provide redis to replace bootstarp_node, You can switch to the fl_async branch to try using redis as a component of dataset discovery.

**Comment by 271983592** [comment]
Thank you very much.
