### ISSUE TITLE
When using baze 5.0.0， error: /bin/bash: $'\r': command not found

### ISSUE THREAD

**Issue by hushanxue** [primihub/primihub#33]
ERROR: /root/.cache/bazel/_bazel_hsx/c5a0b19753becc3200e2a5f87cfd2c2a/external/lib_function2/BUILD.bazel:10:8: Executing genrule @lib_function2//:function2-build failed: (Exit 127): linux-sandbox failed: error executing command
  (cd /root/.cache/bazel/_bazel_hsx/c5a0b19753becc3200e2a5f87cfd2c2a/sandbox/linux-sandbox/33/execroot/__main__ && \
  exec env - \
    PATH=/home/hsx/.opam/4.10.0/bin:/home/hsx/.local/bin:/home/hsx/anaconda3/bin:/home/hsx/anaconda3/condabin:/home/hsx/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/snap/bin \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_hsx/install/c87283ec3a7822eea44f4cecb6db792e/linux-sandbox -t 15 -w /root/.cache/bazel/_bazel_hsx/c5a0b19753becc3200e2a5f87cfd2c2a/sandbox/linux-sandbox/33/execroot/__main__ -w /tmp -w /run/shm -D -- /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
        set -x
        FUNCTION2_ROOT=$(dirname external/lib_function2/CMakeLists.txt)
        cp $FUNCTION2_ROOT/include/function2/function2.hpp bazel-out/k8-fastbuild/bin/external/lib_function2/function2/function2.hpp
    ')
1656642084.665200200: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1656642084.665260800: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1656642084.665663100: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 15992
1656642084.665742300: src/main/tools/linux-sandbox-pid1.cc:641: Pid1Main started
1656642084.665917900: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
1656642084.666076700: src/main/tools/linux-sandbox-pid1.cc:260: working dir: /root/.cache/bazel/_bazel_hsx/c5a0b19753becc3200e2a5f87cfd2c2a/sandbox/linux-sandbox/33/execroot/__main__
1656642084.666113400: src/main/tools/linux-sandbox-pid1.cc:292: writable: /root/.cache/bazel/_bazel_hsx/c5a0b19753becc3200e2a5f87cfd2c2a/sandbox/linux-sandbox/33/execroot/__main__
1656642084.666128100: src/main/tools/linux-sandbox-pid1.cc:292: writable: /tmp
1656642084.666140600: src/main/tools/linux-sandbox-pid1.cc:292: writable: /run/shm
1656642084.666237100: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /
1656642084.666252700: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /init
1656642084.666260300: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev
1656642084.666267100: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/pts
1656642084.666274100: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys
1656642084.666280300: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup
1656642084.666289500: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/unified
1656642084.666297000: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/cpuset
1656642084.666303700: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/cpu
1656642084.666310000: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/cpuacct
1656642084.666315800: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/blkio
1656642084.666322700: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/memory
1656642084.666356800: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/devices
1656642084.666364100: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/freezer
1656642084.666370300: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/net_cls
1656642084.666376800: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/perf_event
1656642084.666383100: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/net_prio
1656642084.666389100: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/hugetlb
1656642084.666395300: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/pids
1656642084.666401400: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/rdma
1656642084.666407900: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc
1656642084.666413200: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc/sys/fs/binfmt_misc
1656642084.666422800: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run
1656642084.666428600: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/lock
1656642084.666434500: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /run/shm
1656642084.666440600: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user
1656642084.666467400: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /usr/lib/wsl/drivers
1656642084.666475700: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /usr/lib/wsl/lib
1656642084.666481200: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /mnt/wsl
1656642084.666488500: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /mnt/c
1656642084.666494800: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /mnt/d
1656642084.666500700: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /mnt/e
1656642084.666533900: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /mnt/f
1656642084.666550000: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /root/.cache/bazel/_bazel_hsx/c5a0b19753becc3200e2a5f87cfd2c2a/sandbox/linux-sandbox/33/execroot/__main__
1656642084.666581600: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /root/.cache/bazel/_bazel_hsx/c5a0b19753becc3200e2a5f87cfd2c2a/sandbox/linux-sandbox/33/execroot/__main__
1656642084.666594400: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /tmp
1656642084.666604000: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /run/shm
1656642084.666742500: src/main/tools/linux-sandbox-pid1.cc:451: calling fork...
1656642084.667313800: src/main/tools/linux-sandbox-pid1.cc:481: child started with PID 2
/bin/bash: $'\r': command not found
1656642084.675113200: src/main/tools/linux-sandbox-pid1.cc:498: wait returned pid=2, status=0x7f00
1656642084.675130100: src/main/tools/linux-sandbox-pid1.cc:516: child exited normally with code 127
1656642084.675748300: src/main/tools/linux-sandbox.cc:233: child exited normally with code 127
INFO: Elapsed time: 0.484s, Critical Path: 0.13s

**Comment by hobo0cn** [comment]
Let's me guess. Are you build on Windows WSL?

**Comment by hushanxue** [comment]
> 

Yes，windows WSL, ubuntu 20.04.4 LTS

**Comment by hobo0cn** [comment]
The reason is Windows use /r/n as newline, but linux use /n. Try to use dos2unix.exe change bazel file format. You should run:
```
 dos2unix.exe bazel/*
```
before bazel build.

**Comment by hushanxue** [comment]
> 

Thanks, it works.  I use dos2unix  in Ubuntu，change all files in  bazel's directory   to unix。
