### ISSUE TITLE
How to use version 1.6.2 to do Homo LR Demo

### ISSUE THREAD

**Issue by 271983592** [primihub/primihub#330]
I use version 1.6.2 to do "Homo LR Demo".  Demo code is as follow:

import primihub as ph
from primihub.FL.model.logistic_regression.homo_lr import run_host_party, run_guest_party,run_arbiter_party
from primihub.client import primihub_cli as cli
cli.init(config={"node": "192.168.146.136:50050", "cert": ""})
cli.async_remote_execute((run_host_party, ), (run_guest_party, ))

But the error log from Host(50051) is as follow:

![图片](https://user-images.githubusercontent.com/58243013/223002104-89198c9d-78b4-487f-ad8a-225fa36044ce.png)

**Comment by xuefeng-xu** [comment]
Hi,

Thank you for pointing out this bug. I assume you refer to this page [https://docs.primihub.com/docs/advance-usage/python-sdk/homo-lr/](https://docs.primihub.com/docs/advance-usage/python-sdk/homo-lr/). However, this code is outdated. I suggest you refer to this page [https://docs.primihub.com/docs/advance-usage/fedreated-learning/homo-lr-dpsgd](https://docs.primihub.com/docs/advance-usage/fedreated-learning/homo-lr-dpsgd). You can replace the python script with `homo_lr.py`, `homo_lr_dpsgd.py`, or `homo_lr_paillier.py`.

Let us know if you have any other questions.

**Comment by xuefeng-xu** [comment]
@271983592  We have updated the online doc.
