### ISSUE TITLE
node can not work after docker compose(always restarting)

### ISSUE THREAD

**Issue by whatsmore** [primihub/primihub#331]
**Describe the bug**
> git clone
> cd primihub
> docker compose up -d
> docker ps

find primihub-node0、primihub-node1、primihub-node2 always restarting

**Expected behavior**
hope node works

**Log output**
docker logs:
`./primihub-node: error while loading shared libraries: libmysqlclient.so.21: cannot open shared object file: No such file or directory`
`./primihub-node: error while loading shared libraries: libmysqlclient.so.21: cannot open shared object file: No such file or directory`
`./primihub-node: error while loading shared libraries: libmysqlclient.so.21: cannot open shared object file: No such file or directory`
`./primihub-node: error while loading shared libraries: libmysqlclient.so.21: cannot open shared object file: No such file or directory`
`./primihub-node: error while loading shared libraries: libmysqlclient.so.21: cannot open shared object file: No such file or directory`
`./primihub-node: error while loading shared libraries: libmysqlclient.so.21: cannot open shared object file: No such file or directory`
`./primihub-node: error while loading shared libraries: libmysqlclient.so.21: cannot open shared object file: No such file or directory`

**Enviroment (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core) （alicloud ecs）
 - Version of Primihub:github:master
 - Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq arch_capabilities

**Comment by fuxingbit** [comment]
Please check the image version，If it is not the latest, please pull the latest image.

**Comment by fuxingbit** [comment]
There is something wrong with the image, please run `docker pull primihub/primihub-node` and try again.

**Comment by whatsmore** [comment]
the version of image is latest
`REPOSITORY                         TAG                                         IMAGE ID       CREATED        SIZE`
`primihub/primihub-node             latest                                      ca7b3faf2bf9   3 weeks ago    3.82GB`
`primihub/redis                     latest                                      3e12e2ceb68f   3 months ago   117MB`
`reg.docker.alibaba-inc.com/nueva-stack/nueva   ANOLIS-ACI-v2.0.9-20221107-172914-5887049   c4001fd73b60   4 months ago   2.44GB`
`primihub/simple-bootstrap-node     1.0                                         516352269eb0   9 months ago   31.1MB`

**Comment by fuxingbit** [comment]
The image has been updated.please run `docker pull primihub/primihub-node` to update the latest image，or use tag 1.6.2
![image](https://user-images.githubusercontent.com/26339492/224597017-63b846e8-eaa9-4048-9f9c-aff1c4f4536c.png)

**Comment by whatsmore** [comment]
it works
thx
