### ISSUE TITLE
The task of PSI failed in docker-compose

### ISSUE THREAD

**Issue by Swatermelon1119** [primihub/primihub#35]
I use the demo code in doc[https://docs.primihub.com/docs/advance-usage/create-tasks/psi-task](url)

“./primihub-cli --task_type=3 --params="clientData:STRING:0:psi_client_data,serverData:STRING:0:psi_server_data，clientIndex:INT32:0:0,serverIndex:INT32:0:1,psiType:INT32:0:0,outputFullFilename:STRING:0:/data/result/psi_result.csv" --input_datasets="clientData,serverData"
”

node0_primihub         | Could not create logging file: No such file or directory
node0_primihub         | COULD NOT CREATE A LOGGINGFILE 20220703-025230.1!Could not create logging file: No such file or directory
node0_primihub         | COULD NOT CREATE A LOGGINGFILE 20220703-025230.1!E20220703 02:52:30.917066    26 service.cc:242]  🔍 ⏱️  Timeout while searching meta list.

the log shows that the demo task  timeout

**Comment by yongganhangxing** [comment]
Thank you for submitting your issue.  The reason for task timeout is that the scheduling node didn't find nodes that separately registered clientData and serverData. So far we have found two things can that cause the error, one is the program simple-bootstrap-node is not running on the host, the other is that there is a bug  when running primihub on centos, we suggest users run primihub on ubuntu before we fix the bug on centos. If you have none of the two, we will keep trying to solve the issue.

**Comment by hobo0cn** [comment]
The root cause is a problem with the Chain DOCKER-USER setting of iptables on centos. Please list your iptables.

**Comment by hobo0cn** [comment]
@Swatermelon1119 Still have this problem?

**Comment by hobo0cn** [comment]
No response, I'll close this issue.
