### ISSUE TITLE
Does the deployment support Centos operating system?

### ISSUE THREAD

**Issue by sky999999** [primihub/primihub#368]
请问Primihub支持Centos操作系统吗
Does the deployment support Centos operating system?

**Comment by fuxingbit** [comment]
centos7暂不支持编译，docker镜像运行没有问题

**Comment by phoenix20162016** [comment]
the latest develop has already support centos, 
now you can  follow the step described at the doc  https://docs.primihub.com/docs/advance-usage/start/build

enjoy it.
