### ISSUE TITLE
The performance of PIR and PSI

### ISSUE THREAD

**Issue by whatsmore** [primihub/primihub#369]
Hello, primihub
can you provide some information about the performance of PIR and PSI in primihub under different quantity levels and Network bandwidths?
thx

**Comment by Keepmoving-ZXY** [comment]
There are some PSI benchmark results on the network that has 100Mb bandwidth and about 1ms latency:
10w vs 10w use 0.770s, 
100w vs 100w use 7.225s,
500w vs 500w use 36.68s.

And we are working to optimize the PSI protocol these days, please wait for more reference results.
