### ISSUE TITLE
python3-dev has installed，but an error occurs

### ISSUE THREAD

**Issue by hushanxue** [primihub/primihub#37]
I have install  python3-dev, when i compile using bazel,  some errors show me to install pyhon2-dev，I don't why, python3 not enough?
---------------------------------------------------------------------------------------------------------------------------------------
bazel-out/k8-fastbuild/bin/external/local_config_python/_python3/_python3_include/object.h:430: error: undefined reference to '_Py_Dealloc'
external/pybind11/include/pybind11/detail/../detail/common.h:983: error: undefined reference to 'PyExc_TypeError'
external/pybind11/include/pybind11/detail/../detail/common.h:983: error: undefined reference to 'PyErr_SetString'
external/pybind11/include/pybind11/detail/../detail/common.h:987: error: undefined reference to 'PyExc_RuntimeError'
external/pybind11/include/pybind11/detail/../detail/common.h:987: error: undefined reference to 'PyErr_SetString'
external/pybind11/include/pybind11/detail/../detail/common.h:1046: error: undefined reference to 'PyErr_Fetch'
external/pybind11/include/pybind11/detail/../detail/common.h:1047: error: undefined reference to 'PyErr_Restore'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:384: error: undefined reference to 'PyErr_Fetch'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:396: error: undefined reference to 'PyErr_Restore'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:448: error: undefined reference to 'PyErr_Fetch'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:449: error: undefined reference to 'PyErr_NormalizeException'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:451: error: undefined reference to 'PyException_SetTraceback'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:457: error: undefined reference to 'PyErr_SetString'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:459: error: undefined reference to 'PyErr_Fetch'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:460: error: undefined reference to 'PyErr_NormalizeException'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:462: error: undefined reference to 'PyException_SetCause'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:463: error: undefined reference to 'PyException_SetContext'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:464: error: undefined reference to 'PyErr_Restore'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:522: error: undefined reference to 'PyObject_HasAttrString'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:546: error: undefined reference to 'PyObject_GetAttrString'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:576: error: undefined reference to 'PyObject_SetAttrString'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:613: error: undefined reference to 'PyUnicode_FromString'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:618: error: undefined reference to 'PyDict_GetItemWithError'
external/pybind11/include/pybind11/detail/../detail/../pytypes.h:620: error: undefined reference to 'PyErr_Occurred'

**Comment by lzw9560** [comment]
Too little context, please provide more context to help us troubleshoot.

**Comment by lzw9560** [comment]
It may be that there are too many local python versions, resulting in the correct python dynamic library not being executed when compiling, try to clean up the environment, and only keep the only correct python version

**Comment by zjning95** [comment]
Please refer to the Dockerfile file, the default python-dev also needs to be installed.

**Comment by hushanxue** [comment]
> Please refer to the Dockerfile file, the default python-dev also needs to be installed.

er, i use bazel to compile, not using docker.

**Comment by lzw9560** [comment]
Yes, it is, compiling with bazel also requires python2-dev to be installed and also requires python-dev.

**Comment by hushanxue** [comment]
> Yes, it is, compiling with bazel also requires python2-dev to be installed and also requires python-dev.

I installed python-dev, python3-dev, python2-dev,  but it not work, am I need [ bazel  clean ], then [bazel build] ?

**Comment by zjning95** [comment]
If you are not using python 3.9, replace python 3.9 in the pre_build.sh file with your python version and run it

**Comment by zjning95** [comment]
The python version needs to be greater than 3.6

**Comment by hobo0cn** [comment]
@hushanxue Still has this problem?
Try show you python config use `python3-config --ldflags`, and copy output change content this line
https://github.com/primihub/primihub/blob/5f05c8a00f6d4c1d28a7e778683405749c50f367/BUILD.bazel#L527

DO NOT forget type `-lpython3.9` link option.

**Comment by hobo0cn** [comment]
Pls follow comment above, I close this.
