### ISSUE TITLE
执行 deploy.sh 报错Error response from daemon: Invalid address 172.28.1.30: It does not belong to any of this network's subnets

### ISSUE THREAD

**Issue by mengxiangyu-png** [primihub/primihub#380]
**Describe the bug**
Error response from daemon: Invalid address 172.28.1.30: It does not belong to any of this network's subnets

[root@localhost docker-deploy]# sh deploy.sh 
docker installed
Docker Compose version v2.6.0
docker-compose installed
1.6.4: Pulling from primihub/primihub-fusion
Digest: sha256:591e2d8e0f8e684fa4e6764ef200cb22d030f3e5e764ddbdb8a1264a930f49e2
Status: Image is up to date for primihub/primihub-fusion:1.6.4
docker.io/primihub/primihub-fusion:1.6.4
1.6.4: Pulling from primihub/primihub-platform
Digest: sha256:721bd58c64df3e61b80b6be1d8bc5b8f2ecd91e4a9e1309b379cd52a2f796906
Status: Image is up to date for primihub/primihub-platform:1.6.4
docker.io/primihub/primihub-platform:1.6.4
1.6.4: Pulling from primihub/primihub-web
Digest: sha256:224b169e706b18c8f6cdc532ccaf9902f30a0fc093f309f46bfdf1efc569b769
Status: Image is up to date for primihub/primihub-web:1.6.4
docker.io/primihub/primihub-web:1.6.4
1.6.4: Pulling from primihub/primihub-node
Digest: sha256:f23c659e71e5ba3964acaf04eb69b8bff231cca07022c2abbc679fbea31cdaa5
Status: Image is up to date for primihub/primihub-node:1.6.4
docker.io/primihub/primihub-node:1.6.4
v2.0.4: Pulling from primihub/nacos-server
Digest: sha256:6dfbd52d675f804d11f370b42a1f969f5d9557c56fe091a62de3051d3d115d6e
Status: Image is up to date for registry.cn-beijing.aliyuncs.com/primihub/nacos-server:v2.0.4
registry.cn-beijing.aliyuncs.com/primihub/nacos-server:v2.0.4
3.6.15-management: Pulling from primihub/rabbitmq
Digest: sha256:d1e6b70b28b9fe6c42ba86c059bd249677583bb62cb25f6f982649bd7ae6976b
Status: Image is up to date for registry.cn-beijing.aliyuncs.com/primihub/rabbitmq:3.6.15-management
registry.cn-beijing.aliyuncs.com/primihub/rabbitmq:3.6.15-management
7: Pulling from library/redis
Digest: sha256:92b8b307ee28ed74da17578064c73307ad41e43f422f0b7e4e91498b406c59e3
Status: Image is up to date for redis:7
docker.io/library/redis:7
5.7: Pulling from primihub/mysql
Digest: sha256:398f124948bb3d5789c0ac7c004d02e6d9a3ae95aa9804d7a3b33a344ff3c9cd
Status: Image is up to date for registry.cn-beijing.aliyuncs.com/primihub/mysql:5.7
registry.cn-beijing.aliyuncs.com/primihub/mysql:5.7
Using default tag: latest
latest: Pulling from primihub/loki
Digest: sha256:d69f377ecfdbb3f72086a180dcd7c2f02c795cf1867bbeb61606b42a8d41a557
Status: Image is up to date for registry.cn-beijing.aliyuncs.com/primihub/loki:latest
registry.cn-beijing.aliyuncs.com/primihub/loki:latest
[+] Running 0/3
 ⠦ Container redis  Starting                                                                                                                                                                                 0.6s
 ⠦ Container loki   Starting                                                                                                                                                                                 0.6s
 ⠦ Container mysql  Starting                                                                                                                                                                                 0.6s
Error response from daemon: Invalid address 172.28.1.30: It does not belong to any of this network's subnets

**Comment by fuxingbit** [comment]
检查docker-compose 354行，改成172.29.1.30

**Comment by fuxingbit** [comment]
1. docker-compose down
2. 删除 data/mysql 目录
3. 执行
```
sed -i 's/172.28/172.29/g' data/initsql/others.sql
sed -i 's/172.28/172.29/g' docker-compose.yml
sed -i 's/172.28/172.29/g' config/primihub_node*
```
4. docker-compose up -d

**Comment by mengxiangyu-png** [comment]
sed -i 's/172.28/172.29/g' docker-compose.yml
sed -i 's/172.28/172.29/g' config/primihub_node*  还是和网关有关，执行完这个可以了
