### ISSUE TITLE
我在 sh deploy.sh部署的时候提示提示

### ISSUE THREAD

**Issue by mengxiangyu-png** [primihub/primihub#384]
**Describe the bug**
 ? Network docker-deploy_primihub_net  Error                                                                                                                              0.0s
failed to create network docker-deploy_primihub_net: Error response from daemon: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-226f4c00e324 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))

![1](https://user-images.githubusercontent.com/57181576/232057392-ce1a0ebf-c55c-4fa6-95c4-443725b4470d.png)

**Comment by fuxingbit** [comment]
什么系统？你前面不是部署成功了么？安装下iptables试试吧

**Comment by mengxiangyu-png** [comment]
我自己的虚拟机 Red Hat 4.8.5-36，centoiptables我安装了，没好用，开始是登录了，但是后来资源新增不了，然后又刷了下你说的脚本,好像是对sql语句也替换成172.29，然后就这样。

**Comment by fuxingbit** [comment]
执行deploy.sh前有执行docker-compose down么？现在直接执行docker-compose up -d启动呢

**Comment by mengxiangyu-png** [comment]
谢谢，现在成功了。之前我的操作好像是先删除所有docker ，然后把文件重新下载下来，然后按照你的脚本做的，然后我把脚本改成了sed -i 's/172.28/172.29/g' data/initsql/*.sql   。之前没成功，但是现在成功了，是不是系统部署完后,有的服务得一会才能真正启动完成，控制台需要得一会才能访问，要不然报404，现在我看终于登陆进去了，然后创建了一个资源也成功，非常感谢

**Comment by mengxiangyu-png** [comment]
感谢
