### ISSUE TITLE
虚拟机上运行了好久了，但是突然报错了kernel:NMI watchdog: BUG: soft lockup - CPU#3 stuck for 23s! [java:102195]

### ISSUE THREAD

**Issue by mengxiangyu-png** [primihub/primihub#387]
**Describe the bug**
docker logs -f primihub-node0

........
Message from syslogd@localhost at Apr 15 10:22:13 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#3 stuck for 23s! [java:102195]

Message from syslogd@localhost at Apr 15 10:22:13 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#1 stuck for 33s! [java:81590]

Message from syslogd@localhost at Apr 15 10:22:13 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#2 stuck for 33s! [java:94258]

Message from syslogd@localhost at Apr 15 10:22:13 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#0 stuck for 33s! [nginx:77370]

**Comment by fuxingbit** [comment]
尽量找个物理机测试吧，可以把虚拟机的cpu设置高一些试试

**Comment by mengxiangyu-png** [comment]
好的。谢谢，那我试试
