### ISSUE TITLE
docker部署的方式，无法访问

### ISSUE THREAD

**Issue by mengxiangyu-png** [primihub/primihub#397]
**Describe the bug**
服务启动后，页面30811可以打开，但是报404错误，看日志nacos启动报错了，且nacos的8848无法访问
![image](https://user-images.githubusercontent.com/57181576/232759550-1ce41712-1d5f-4891-b564-273abb91d80e.png)
![image](https://user-images.githubusercontent.com/57181576/232759775-b9aa2632-ddfe-4b13-8f4f-3fc4a5fd7c3c.png)
![image](https://user-images.githubusercontent.com/57181576/232759893-8be0eff1-dacf-4a82-8e3e-c370943a37cd.png)
困扰我好几天了，可以帮我看看嘛

**Comment by mengxiangyu-png** [comment]
因为之前好用过，但是和那个是一样的方式，不知道哪里弄错了

**Comment by fuxingbit** [comment]
单独重启下nacos ，docker restart nacos-server，看nacos日志能否正常启动？

**Comment by fuxingbit** [comment]
nacos启动正常后，别的服务会自动重启

**Comment by fuxingbit** [comment]
或者整个目录删掉后，重启下载安装包，nacos这个问题有做修复

**Comment by mengxiangyu-png** [comment]
老师，不行啊，之前我用重启nacos的方式好用过，现在重新拉取镜像后又 不行了

**Comment by fuxingbit** [comment]
不要重复提issue

**Comment by fuxingbit** [comment]
可以停止服务后再下载新的安装包，加了服务的健康状态检查，帮忙测试一下

**Comment by mengxiangyu-png** [comment]
![image](https://user-images.githubusercontent.com/57181576/233113017-d3b29b67-a930-4b6c-8fdd-91d0a39f3723.png)
geng更新完了，有效果
