### ISSUE TITLE
example task run success, but some error in log

### ISSUE THREAD

**Issue by ychy00001** [primihub/primihub#4]
Use README.md execute task command, task maybe execute success,  I found some errors in the log. Is that normal？
```
docker run --network=host -it primihub/primihub-node:1.0.5  /app/primihub-cli  --server=127.0.0.1:8050
```

```
node0_primihub           | 22.06.08 10:51:01.448706  Error     Plaintext  received_pid=QmP2C45o2vZfy1JXWFZDUEzrQCigMtd4r3nesvArV8dFKd, p.value()=QmdSyhb8eR9dDSR5jjnRoTDBwpBCSAjT7WueKJ9cQArYoA
node0_primihub           | 22.06.08 10:51:01.449584  Error     Plaintext  error happened while establishing a Plaintext session: Received peer id doesn't match actual peer id
```

**Comment by hobo0cn** [comment]
A p2p network can setup multiple bootstrap nodes. In the test configuration we setup two, but only one is actually started in the docker compose service. This error is an error of the p2p network layer and does not affect the execution of MPC tasks. Maybe the error message makes people nervous.
