### ISSUE TITLE
选择【模型评估】流程节点，单击开始，报错“运行失败，评估模型无入参数信息”

### ISSUE THREAD

**Issue by pxyfxun** [primihub/primihub#454]
**Describe the bug**
创建项目后，创建任务时，选择【模型评估】流程后，单击开始，报错“运行失败，评估模型无入参数信息”

**Expected behavior**
希望能正常支持【模型评估】流程节点加入后的运行

![image](https://github.com/primihub/primihub/assets/29222692/8d14cbff-09ce-4c5e-8fd3-7408376f9f46)

**Comment by leiyannan** [comment]
暂时不支持该组件
