### ISSUE TITLE
docker-compose up -d failed

### ISSUE THREAD

**Issue by mingo0117** [primihub/primihub#47]
I followed the document(https://docs.primihub.com/docs/quick-start), and node 0,1,2  got the following error after execute "docker-compose up -d":
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file: /app/primihub_node1.yaml

why?

**Comment by zjning95** [comment]
Please use the latest develop branch.

**Comment by hobo0cn** [comment]
Duplicate issue : https://github.com/primihub/primihub/issues/45

**Comment by hobo0cn** [comment]
We'll update quick start document.

**Comment by mingo0117** [comment]
I‘m using the latest develop branch, the problem remains,  just executed 'docker-compose up -d'

**Comment by zjning95** [comment]
Confirm that you are using the docker-compose.yaml file from the develop branch?
![image](https://user-images.githubusercontent.com/26339492/177789683-0a340720-075c-42f5-a472-730939b5fa98.png)
