### ISSUE TITLE
通过本地编译启动方式测试FL任务时，总是提示“ImportError: /usr/local/lib/python3.8/lib-dynload/_posixsubprocess.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyTuple_Type”

### ISSUE THREAD

**Issue by shuizhongmose** [primihub/primihub#471]
问题描述：
通过本地编译启动方式来测试FL任务时，总是提示`ImportError: /usr/local/lib/python3.8/lib-dynload/_posixsubprocess.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyTuple_Type`。

尝试过方法：
已经尝试过重新编译python，重新安装所有第三方库，问题仍然无法解决。

日志如下：
- 启动界面日志如下：
 
![image](https://github.com/primihub/primihub/assets/8891482/11f164f2-b91c-4025-8cb8-68ce97ac0f97)

- server端错误日志如下：

![image](https://github.com/primihub/primihub/assets/8891482/46863a38-7723-41fc-9c5b-5a65ead760bf)

操作步骤：
1、通过如下方式安装FL任务环境：
```
cd primihub/python
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
python setup.py install --user
```
2、编译方式下，通过 start-server.sh方式启动3个节点。
3、启动任务命令是：`./bazel-bin/cli --server="127.0.0.1:50050" --task_config_file="example/fl_hetero_xgb_task_conf.json"`

**Comment by fuxingbit** [comment]
你是使用的什么系统？如果是centos或者ubuntu，可以参考[这里](https://docs.primihub.com/docs/advance-usage/start/build)配置python环境，如果是别的系统，可以尝试通过miniconda安装python，参考[这里](https://m74hgjmt55.feishu.cn/docx/FmnSdtDLMoyGLMxffVqcqEZWnFg)

**Comment by shuizhongmose** [comment]
> 你是使用的什么系统？如果是centos或者ubuntu，可以参考[这里](https://docs.primihub.com/docs/advance-usage/start/build)配置python环境，如果是别的系统，可以尝试通过miniconda安装python，参考[这里](https://m74hgjmt55.feishu.cn/docx/FmnSdtDLMoyGLMxffVqcqEZWnFg)

是CentOS8，目前可以测试MPC、PSI和PIR的功能，就是无法测试FL。

**Comment by phoenix20162016** [comment]
> > 你是使用的什么系统？如果是centos或者ubuntu，可以参考[这里](https://docs.primihub.com/docs/advance-usage/start/build)配置python环境，如果是别的系统，可以尝试通过miniconda安装python，参考[这里](https://m74hgjmt55.feishu.cn/docx/FmnSdtDLMoyGLMxffVqcqEZWnFg)
> 
> 是CentOS8，目前可以测试MPC、PSI和PIR的功能，就是无法测试FL。

follow the instruction as mentioned, does your problem have been resolved?

**Comment by shuizhongmose** [comment]
系统是CentOS8，将python升级到3.9以后，出现`undefined symbol: PyFloat_Type`错误。打算直接转到ubuntu20再测试了。

**Comment by fuxingbit** [comment]
```
python_lib_path=$(dirname $(dirname $(which python)))
export LD_LIBRARY_PATH=${python_lib_path}/lib:${LD_LIBRARY_PATH}
```
找到你python lib的路径，参照上面的命令把这个路径加到LD_LIBRARY_PATH中，将以上两行加到start_server.sh脚本中
