### ISSUE TITLE
An Error occured after command "docker-compose up"

### ISSUE THREAD

**Issue by fish1968** [primihub/primihub#5]
# The error message is shown below
```
$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'node1'
Unsupported config option for networks: 'testing_net'
```
I tried to re-download the whole primihub repository, and executge the command again, while the error still occurs.

## my docker version
```
$ docker version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~18.04.3
 Built:             Mon Nov  1 01:04:14 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu5~18.04.3
  Built:            Fri Oct 22 00:57:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.5-0ubuntu3~18.04.2
  GitCommit:
 runc:
  Version:          1.0.1-0ubuntu2~18.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```
## my docker-compose version
```
$ sudo docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```
## my linux's information
```
yabin@server-virtual-machine:~/primihub$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

I am not familiar with docker things, so please forgive me if it is a naive question and give some guides, thx.

**Comment by hobo0cn** [comment]
Upgrade or reinstall the latest Docker and docker-compose. Please refer to：[Install docker on Ubuntu](https://docs.docker.com/engine/install/ubuntu/) and [docker-compose installation](https://docs.docker.com/compose/install/)

**Comment by hobo0cn** [comment]
We will highlight the installed version of docker in the documentation.

**Comment by fish1968** [comment]
> We will highlight the installed version of docker in the documentation.

Werid，I could easily run it on my windows laptop, while the linux one just fails.

**Comment by fish1968** [comment]
> 
```
docker-compose up
```
While it could start, it stuck on a status of finding ipv6 address
![image](https://user-images.githubusercontent.com/62780813/172792129-0d7a4011-6aa6-43ed-b296-029d26b447bd.png)
😢

**Comment by hobo0cn** [comment]
> Werid，I could easily run it on my windows laptop, while the linux one just fails.
I wonder, will there be a video tutorial in future? That will help newbies like me, I guess.

I guess your docker application on windows is a relatively new version. The linux docker version you mentioned above is very old

**Comment by hobo0cn** [comment]
I'll close this if no other questions.:)
