### ISSUE TITLE
Failed to open file from primihub-platform

### ISSUE THREAD

**Issue by mingo0117** [primihub/primihub#53]
I launched primihub by `docker-compose up` , and the branch is `develop`.
I passed a resource by primihub-platform, and the node can receive it through grpc, but the opening failed as follows: 

```
I20220710 03:08:52.751906     1 node.cc:196]  💻 Node listening on port: 50050

I20220710 03:10:41.090735    20 ds.cc:26] start to create dataset.

Failed to open file: /Users/shuming/data/upload/1/2022071011/e03ca5f4-eab6-49f5-83b9-80c2a949748c.csv

```
The resource is in attachment.
[e03ca5f4-eab6-49f5-83b9-80c2a949748c.csv](https://github.com/primihub/primihub/files/9078367/e03ca5f4-eab6-49f5-83b9-80c2a949748c.csv)

**Comment by jenlives** [comment]
https://github.com/primihub/primihub-deploy/blob/main/docker-deploy/docker-compose.yaml  
Is it started by this docker-compose?

**Comment by mingo0117** [comment]
> https://github.com/primihub/primihub-deploy/blob/main/docker-deploy/docker-compose.yaml Is it started by this docker-compose?

No，i launched primihub-platform by my IDE（idea），called the primihub node started by docker-compose, and changed some configurations like ports. let me see this you sent，thx.
