### ISSUE TITLE
管理平台1无法使用Github SSO登录

### ISSUE THREAD

**Issue by LawRachel** [primihub/primihub#567]
**Describe the bug**
从官网的【管理平台体验】区点击进入【管理平台一】登录页后，点击Github SSO登录、确认同意授权后，报错120授权登录失败
![image](https://github.com/primihub/primihub/assets/101253617/13c0a592-2e67-4a0c-a770-a85e7aa2347c)
报错：
{"code":120,"msg":"授权登录失败:授权登录失败:github授权登录失败-配置异常,请尝试联系我们!"}
但有时刷新后又可以直接进入管理平台页面。

**Log output**
{"code":120,"msg":"授权登录失败:授权登录失败:github授权登录失败-配置异常,请尝试联系我们!"}

**Enviroment (please complete the following information):**
 - OS: Win10
 - Arch: x86
 - Browser: Brave
 - Version of Primihub: v1.6.6 node1

**Comment by likehabits** [comment]
此问题是因为服务器代理http请求github授权超时导致的。我们正在修复中
