### ISSUE TITLE
隐私算子相关问题

### ISSUE THREAD

**Issue by zby1997** [primihub/primihub#569]
1. 看到文档里说到平台支持四则运算和求最大最小值，这些算法的实现思路是来自于哪边文章？
2. 如果我想实现安全数据大小比较，比如三方分别持有a和b的秘密共享，通过本地计算减法最终和0进行比较得到结果，这个思路平台是否有相关实现呢

**Comment by Keepmoving-ZXY** [comment]
1.涉及到了布尔分享和布尔电路相关知识，这些内容可以在aby3协议论文中可以找到；
2.平台的实现思路是：三方联合评估PPA电路（电路的输入是`a`和`-b`的秘密分享），可以得到MSB的布尔分享，然后将布尔分享揭露并判断是0还是1即可。

**Comment by Keepmoving-ZXY** [comment]
1.https://github.com/primihub/primihub/blob/9203d1c1fe2b06fb07bb0046234840e57374bdcd/src/primihub/operator/aby3_operator.h#L884这里可以看到比较算子的代码实现；
2.我觉得应该是秘密分享会比较快；
