### ISSUE TITLE
Go语言版本的SDK

### ISSUE THREAD

**Issue by LijinPengT** [primihub/primihub#591]
**其他语言版本的SDK**
由于go语言的代码特性和运行优势，非常希望能够出一个go版本的SDK！感谢大佬

**Comment by phoenix20162016** [comment]
如果你对java熟悉的话可以先使用java的sdk，对于go的sdk，这个后续会做相关的评估然后去实现，anyway, 谢谢的你的建议
java sdk 地址：https://github.com/primihub/primihub-platform/tree/develop/primihub-sdk
java sdk使用文档： https://docs.primihub.com/docs/advance-usage/java-sdk/java-usage
