### ISSUE TITLE
M1 mac在python3.8环境下编译错误

### ISSUE THREAD

**Issue by lzfeifei** [primihub/primihub#598]
M1 mac在python3.8环境下编译错误，能请教一下是什么问题吗？
(py38)  ✘ zz@MacBook-Pro  ~/Project_Pyhton/primihub   develop ±  ./pre_build.sh
+ set -e
+ PYTHON_BIN=python3
+ command -v python3
++ python3 -V
++ awk '{print $2}'
++ awk -F . '{print $1}'
+ U_V1=3
++ python3 -V
++ awk '{print $2}'
++ awk -F . '{print $2}'
+ U_V2=8
++ python3 -V
++ awk '{print $2}'
++ awk -F . '{print $3}'
+ U_V3=15
+ echo your python version is : 3.8.15
your python version is : 3.8.15
+ '[' 3 = 3 ']'
+ PYTHON_CONFIG_CMD=python3.8-config
+ command -v python3.8-config
++ python3.8-config --includes
++ awk '{print $1}'
++ awk -F-I '{print $2}'
+ PYTHON_INC_CONFIG=/Users/zf/opt/anaconda3/envs/py38/include/python3.8
+ '[' '!' -d /Users/zf/opt/anaconda3/envs/py38/include/python3.8 ']'
+ pushd third_party
~/Project_Pyhton/primihub/third_party ~/Project_Pyhton/primihub
+ rm -f python_headers
+ ln -s /Users/zf/opt/anaconda3/envs/py38/include/python3.8 python_headers
+ popd
~/Project_Pyhton/primihub
++ python3.8-config --ldflags
+ CONFIG='-L/Users/zf/opt/anaconda3/envs/py38/lib/python3.8/config-3.8-darwin -ldl -framework CoreFoundation'
+ NEWLINE='["-L/Users/zf/opt/anaconda3/envs/py38/lib/python3.8/config-3.8-darwin -ldl -framework CoreFoundation"] + ["-lpython3.8"]'
+ sed -e 's|PLACEHOLDER-PYTHON3.X-CONFIG|["-L/Users/zf/opt/anaconda3/envs/py38/lib/python3.8/config-3.8-darwin -ldl -framework CoreFoundation"] + ["-lpython3.8"]|g' BUILD.bazel
+ mv BUILD.bazel.tmp BUILD.bazel
+ echo done
done
+ '[' '!' -d localdb ']'
+ '[' '!' -d log ']'
++ uname -s
+ KERNEL_NAME=Darwin
++ echo Darwin
++ tr '[:upper:]' '[:lower:]'
+ KERNEL_NAME=darwin
++ uname -m
+ MACHINE_HARDWARE=arm64
+ sed -e 's|PLATFORM_HARDWARE|darwin_arm64|g' Makefile
+ mv Makefile.tmp Makefile
(py38)  zf@MacBook-Pro  ~/Project_Pyhton/primihub   develop ±  make
bazel build --config=darwin_arm64  //:node //:cli //src/primihub/cli:reg_cli //src/primihub/pybind_warpper:linkcontext //src/primihub/pybind_warpper:opt_paillier_c2py //:py_main
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Analyzed 6 targets (1 packages loaded, 49 targets configured).
INFO: Found 6 targets...
ERROR: /private/var/tmp/_bazel_zf/2da5f5da2a518089066378aacaba9d26/external/rules_foreign_cc/toolchains/BUILD.bazel:130:10: BootstrapGNUMake external/rules_foreign_cc/toolchains/make failed: (Exit 77): bash failed: error executing command /bin/bash -c bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/make_tool_foreign_cc/wrapper_build_script.sh

Use --sandbox_debug to see verbose messages from the sandbox
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____
xcrun: error: SDK "macosx13.3" cannot be located
xcrun: error: SDK "macosx13.3" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'macosx13.3'
+ XCODE_VERSION_OVERRIDE=14.3.1.14E300c
+ APPLE_SDK_VERSION_OVERRIDE=13.3
+ APPLE_SDK_PLATFORM=MacOSX
+ ZERO_AR_DATE=1
+ AR=/private/var/tmp/_bazel_zf/2da5f5da2a518089066378aacaba9d26/sandbox/darwin-sandbox/483/execroot/primihub/external/local_config_cc/libtool
+ ARFLAGS=-o
+ CC=/private/var/tmp/_bazel_zf/2da5f5da2a518089066378aacaba9d26/sandbox/darwin-sandbox/483/execroot/primihub/external/local_config_cc/wrapped_clang
+ CFLAGS='-D_FORTIFY_SOURCE=1 -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -DNS_BLOCK_ASSERTIONS=1 DEBUG_PREFIX_MAP_PWD=. -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -mmacosx-version-min=13.3 -no-canonical-prefixes -pthread -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__=redacted -D__TIMESTAMP__=redacted -D__TIME__=redacted -target arm64-apple-macosx'
+ LD=/private/var/tmp/_bazel_zf/2da5f5da2a518089066378aacaba9d26/sandbox/darwin-sandbox/483/execroot/primihub/external/local_config_cc/cc_wrapper.sh
+ LDFLAGS='-lc++ -fobjc-link-runtime -headerpad_max_install_names -no-canonical-prefixes -target arm64-apple-macosx -mmacosx-version-min=13.3 -lc++ -target arm64-apple-macosx'
+ ./configure --without-guile --with-guile=no --disable-dependency-tracking --prefix=/private/var/tmp/_bazel_zf/2da5f5da2a518089066378aacaba9d26/sandbox/darwin-sandbox/483/execroot/primihub/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/make
checking for a BSD-compatible install... /opt/homebrew/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /opt/homebrew/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... /private/var/tmp/_bazel_zf/2da5f5da2a518089066378aacaba9d26/sandbox/darwin-sandbox/483/execroot/primihub/external/local_config_cc/wrapped_clang
checking whether the C compiler works... no
configure: error: in `/private/var/tmp/_bazel_zf/2da5f5da2a518089066378aacaba9d26/sandbox/darwin-sandbox/483/execroot/primihub/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/make.build_tmpdir':
configure: error: C compiler cannot create executables
See `config.log' for more details
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/make_tool_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/make_tool_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/make_tool_foreign_cc/BootstrapGNUMake.log

INFO: Elapsed time: 4.564s, Critical Path: 4.20s
INFO: 50 processes: 11 internal, 39 darwin-sandbox.
FAILED: Build did NOT complete successfully
make: *** [release] Error 1
(py38)  ✘ zz@MacBook-Pro  ~/Project_Pyhton/primihub   develop ± 

**Comment by xuefeng-xu** [comment]
运行`xcrun --sdk macosx --show-sdk-path`，查看是否有path输出

**Comment by lzfeifei** [comment]
> 运行`xcrun --sdk macosx --show-sdk-path`，查看是否有path输出

![image](https://github.com/primihub/primihub/assets/131650481/4114f9f0-5fa7-4c99-bad0-1da02f68ffc5)

**Comment by xuefeng-xu** [comment]
> _____ BEGIN BUILD LOGS _____
xcrun: error: SDK "macosx13.3" cannot be located
xcrun: error: SDK "macosx13.3" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'macosx13.3'

我觉得是因为你没装xcode

我mac上的输出是/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk

**Comment by phoenix20162016** [comment]
用mac自带的appstore 安装下xcode，手动安装可能会有部分依赖会有缺失的情况

**Comment by phoenix20162016** [comment]
@lzfeifei 你的问题是否已经得到解决？
