### ISSUE TITLE
mysql连接报错需要关闭ssl连接

### ISSUE THREAD

**Issue by aaaaaa1** [primihub/primihub#624]
mysql进行连接时报错，如下图：
![I5G%_GCIW7{4WA7_U U2$HR](https://github.com/primihub/primihub/assets/5926342/45deba7c-1602-4cc6-8082-0da8ed56dffa)

您好，由于小白，咨询如何修改代码添加mysql连接时对ssl进行禁用，比如连接参数加上  
 // 设置ssl-mode为DISABLED
    con->setClientOption("ssl-mode", "DISABLED");

**Comment by aaaaaa1** [comment]
![image](https://github.com/primihub/primihub/assets/5926342/a8c01e0e-8bd1-4953-b0af-616f892204a6)
 这块代码看不懂如何修改

**Comment by phoenix20162016** [comment]
@aaaaaa1 你使用的mysql版本是多少
关于如何关闭ssl，可以参考如 https://dev.mysql.com/doc/c-api/5.7/en/mysql-options.html
关于MYSQL_OPT_SSL_MODE （mysql version 5.7.11 or above)的设置
