### ISSUE TITLE
我在单机上部署完，在浏览器打开节点时会弹404

### ISSUE THREAD

**Issue by zzwtop1** [primihub/primihub#649]
![image](https://github.com/primihub/primihub/assets/102272958/92423ef9-6dc0-447b-a7a5-7776102a552e)

**Comment by fuxingbit** [comment]
部署到本地的没有提供注册功能，因为要用我们的验证码通道，可使用默认用户密码 admin / 123456 登录试用

**Comment by zzwtop1** [comment]
![image](https://github.com/primihub/primihub/assets/102272958/f08d2d13-88d9-491b-a3ad-27ca568c8387)

**Comment by zzwtop1** [comment]
这是没部署好吗，登录不进去，部署过程中也没看到有报错

**Comment by zzwtop1** [comment]
![image](https://github.com/primihub/primihub/assets/102272958/27033335-43a4-4512-83f0-211b81851f3b)

**Comment by fuxingbit** [comment]
看下application的日志，没有正常启动

**Comment by zzwtop1** [comment]
![image](https://github.com/primihub/primihub/assets/102272958/17df8737-1dc1-45e3-96a4-7783dcaa0b98)

**Comment by zzwtop1** [comment]
要在哪里看呢？

**Comment by fuxingbit** [comment]
docker logs -f application0

**Comment by zzwtop1** [comment]
![image](https://github.com/primihub/primihub/assets/102272958/cf3ed1c3-8fa8-4bbd-9e1b-c51e8731b476)
这个好像一直在重启

**Comment by fuxingbit** [comment]
[quer](https://docs.primihub.com/docs/advance-usage/deployment/docker-all-in-one) 看这个，确认mysql和nacos的状态是healthy

**Comment by fuxingbit** [comment]
没成功可以再执行一下 docker-compose up -d

**Comment by zzwtop1** [comment]
![image](https://github.com/primihub/primihub/assets/102272958/df0a3843-1036-4f39-b775-08b37e283ccc)
![image](https://github.com/primihub/primihub/assets/102272958/3c623cf9-91e3-47bd-a5a7-1769e44b6b23)
这俩都是正常的但application还是在不断重启
![image](https://github.com/primihub/primihub/assets/102272958/bb901583-bfa5-40ad-b2e8-2e67aaa53f4a)
我准备卸了重装试一下

**Comment by fuxingbit** [comment]
看下日志呀

**Comment by zzwtop1** [comment]
isMultiInstance:false
10:35:04.334 [ERROR] [main] [org.springframework.boot.SpringApplication:834] Application run failed
org.yaml.snakeyaml.parser.ParserException: while parsing a flow mapping
 in 'reader', line 1, column 1:
    {{"model_components":[{"componen ... 
    ^
expected ',' or '}', but got <stream end>
 in 'reader', line 1, column 15610:
     ... value":"","input_values":[]}]}]}

**Comment by zzwtop1** [comment]
防火墙开着有影响吗

**Comment by zzwtop1** [comment]
刚才重新安装创建gateway那一步没显示done就安装完成了

**Comment by fuxingbit** [comment]
是sql的问题，更新了部署脚本，你更新下代码，删除目录下的data/mysql 目录后重新部署
![image](https://github.com/primihub/primihub/assets/26339492/f371d8e7-c715-47e2-be24-ce9ffaa7dbf0)

**Comment by zzwtop1** [comment]
部署完成了，新拉取的文件已经把mysql删除了，现在可以直接git拉取下来安装了
