### ISSUE TITLE
单机部署的，有显示【隐私求交】的目录，点击之后报暂无权限

### ISSUE THREAD

**Issue by zzwtop1** [primihub/primihub#652]
![image](https://github.com/primihub/primihub/assets/102272958/235ffbe7-b820-464a-bb97-40bf3c19141e)

![image](https://github.com/primihub/primihub/assets/102272958/9e59ceb2-1641-4d0f-97ea-5c38a4615de1)

**Comment by fuxingbit** [comment]
在页面 系统设置-角色管理里，编辑超级管理员的权限，把没有勾选的模块勾选上

**Comment by fuxingbit** [comment]
这个权限是数据库里有缺失，已经修复，更新下部署脚本，删除本地部署目录下的data/mysql目录，再重新部署

**Comment by zzwtop1** [comment]
每次docker stop停止服务都很慢，docker-compose down更是直接报错，，，ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.

**Comment by fuxingbit** [comment]
你机器什么配置？这个问题我们没有遇到过

**Comment by zzwtop1** [comment]
看了一下可能是在跑大模型的原因
