### ISSUE TITLE
之前docker-compose单机部署的添加节点信息时一直报超时

### ISSUE THREAD

**Issue by zzwtop1** [primihub/primihub#660]
![image](https://github.com/primihub/primihub/assets/102272958/e7228b9f-49b6-4884-aba0-2abdfc1d9734)
之前一直无法添加，一添加就报超时，现在能添加，但是对方在同意时，又会一直报超时
![image](https://github.com/primihub/primihub/assets/102272958/98f503f7-bd33-4591-8934-95bdb6153ec9)
![803cd1a626939300fbc52d15489ab29](https://github.com/primihub/primihub/assets/102272958/6f4fe858-3482-4c64-a997-2bbd7b7967ef)

**Comment by zzwtop1** [comment]
还有A跟C时能正常添加的，A跟B也能添加，但是B跟C互相添加都会出超时错误

**Comment by zzwtop1** [comment]
本来能够连接的A和B现在断开后，再次申请，也会这样超时

**Comment by zzwtop1** [comment]
![image](https://github.com/primihub/primihub/assets/102272958/fa953d53-2084-4492-8317-b7d843b0d7e5)
现在添加节点信息这边，双方同意拒绝都不行

**Comment by likehabits** [comment]
请检查一下部署版本，最新的版本1.6.11中未发现该问题
