### ISSUE TITLE
docker-compose单机部署之后，安装loki插件之后平台日志还是无法显示详细信息

### ISSUE THREAD

**Issue by Handikang** [primihub/primihub#713]
![image](https://github.com/primihub/primihub/assets/42713276/7834ff9d-900c-4cd2-ac71-0f15e6c1b019)

**Comment by Handikang** [comment]
![image](https://github.com/primihub/primihub/assets/42713276/baee2c86-efde-4f67-aa76-55bdc1ba3c01)

**Comment by fuxingbit** [comment]
1. 检查系统日志有无错误信息，如果有loki的相关错误将daemon.json中的127.0.0.1修改为机器的内网IP
2. 检车启动时是否用bash deploy.sh的方式启动，如果不是，修改nacos中的base.json中的loki IP地址为本机的IP

**Comment by fuxingbit** [comment]
在浏览器f12打开控制台，看能否链接到loki，有无报错信息

**Comment by Handikang** [comment]
你好daemon.json位置在哪里,还有nacos这里的base.json需要重新配置吗
![image](https://github.com/primihub/primihub/assets/42713276/aae062e4-4611-457d-82fe-adf300eaa09e)

**Comment by Handikang** [comment]
![image](https://github.com/primihub/primihub/assets/42713276/d90f7896-91c7-4dcb-92c8-30f69345aa4c)
![image](https://github.com/primihub/primihub/assets/42713276/8d19a873-925e-44b9-bd05-24af2525f9eb)
![image](https://github.com/primihub/primihub/assets/42713276/de7dfc5b-7409-4a37-b795-2a2d8820107d)

这些都修改过了，但是日志还是没能显示出来，然后loki的docker插件也安装过了，想请教一下是哪里的问题导致日志还无法显示出来 @fuxingbit
