### ISSUE TITLE
想问一下平台隐匿查询是在代码仓库的哪一块

### ISSUE THREAD

**Issue by Handikang** [primihub/primihub#717]
![image](https://github.com/primihub/primihub/assets/42713276/4a91d6a9-a9d6-41ff-8d1e-0dfbe52c459f)
还有咱们的隐匿查询是通过什么安全多方计算技术实现的

**Comment by phoenix20162016** [comment]
通过同态实现的keyword pir
具体的实现依赖于APSI库
