### ISSUE TITLE
本地启动编译问题

### ISSUE THREAD

**Issue by Veluriyam** [primihub/primihub#728]
When I started by local compilation, I executed the './pre_build.sh 'script and entered' make 'to compile, but the compilation failed due to network problems, how should I solve it, looking forward to your reply，thanks!
![微信图片_20231207191417](https://github.com/primihub/primihub/assets/101782273/024269f5-c3da-446a-a031-baa038b3bb92)

**Comment by phoenix20162016** [comment]
Add the dep like the follows to workspace
http_archive(
  name = "go_sdk",
  strip_prefix = top dir name of the package,
  urls = [
    "file://  path where your package locate",
  ],
 sha256 = "",
)

**Comment by phoenix20162016** [comment]
@Veluriyam 你的问题解决了吗
