### ISSUE TITLE
关于模型训练后出现free( ): invalid pointer问题

### ISSUE THREAD

**Issue by mtl802** [primihub/primihub#732]
使用python其他包，自写的一些算法，通过python setup.py install生成包后转移到已经搭建好的node容器中。
点击前端的训练之后会出现可以训练模型，但是无法释放的问题。

安装的python包有些和primihub需求的包版本有冲突，手动进行了更新。

![4a318a4a5fbbb23497292a223f8dfbb](https://github.com/primihub/primihub/assets/20579710/a0b00044-455d-475f-ae69-94720e6e60ed)

**Comment by phoenix20162016** [comment]
辛苦使用ulimit -c unlimited 打开生成core文件，通过gdb看下coredump的信息

**Comment by mtl802** [comment]
![image](https://github.com/primihub/primihub/assets/20579710/75b30487-59e7-4bfb-90fa-a10aa5c76509)
这个应该怎么操作

**Comment by phoenix20162016** [comment]
gdb path/task_main core.xxx

bt

**Comment by phoenix20162016** [comment]
@mtl802 问题解决了吗

**Comment by mtl802** [comment]
> @mtl802 问题解决了吗

抱歉，忘了回复了，似乎是包版本的冲突，重新创建环境之后解决了
