### ISSUE TITLE
运行python example出现ph_secure_lib找不到

### ISSUE THREAD

**Issue by JcobCN** [primihub/primihub#746]
Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the past issues](https://github.com/primihub/primihub/issues).

**Describe the bug**

1.7.0版本，通过docker-compose up -d 启动测试节点

运行
```sh
./primihub-cli --task_config_file="example/python_code_3pc.json"
```
出现错误
```sh
I20240109 11:28:18.924561   415 cli.cc:403] party: "Bob" status: FAIL message: "ModuleNotFoundError: No module named 'ph_secure_lib'

At:
  /usr/local/lib/python3.8/dist-packages/primihub/MPC/statistics.py(1): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  <string>(3): <module>
  /usr/local/lib/python3.8/dist-packages/primihub/engine/engine.py(29): run
  /usr/local/lib/python3.8/dist-packages/primihub/executor.py(71): run
  /usr/local/lib/python3.8/dist-packages/primihub/executor.py(89): execute_py
"
```

**Enviroment**

- OS windows11 Ubuntu22.04 WSL

**docker images**
```sh
primihub/primihub-meta   latest    90de503ae93d   5 weeks ago   423MB
primihub/primihub-node   latest    cbf0e99f9e2b   5 weeks ago   2.65GB
```

**Comment by phoenix20162016** [comment]
进入docker里面，查看下ph_secure_lib.so 是否存在，存在的情况下，查看下python的默认路径 import sys, print(sys.path)

**Comment by JcobCN** [comment]
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']

find / -name ph_secure_lib* 找不到

**Comment by phoenix20162016** [comment]
registry.cn-beijing.aliyuncs.com/primihub/primihub-node:1.7.0 初步怀疑你拉取的镜像有问题, 正常情况下这个是存在的
![image](https://github.com/primihub/primihub/assets/18574396/817b6986-54ab-4b9c-bd59-7900b960518f)

**Comment by JcobCN** [comment]
我贴了docker images的hash。

docker-compose.yaml
```yaml
    node0:
      image: ${REGISTRY:-docker.io}/primihub/primihub-node:${TAG:-latest}
````
我是先clone的代码库，然后切换到1.7.0这个release tag再起的容器。
```sh
git checout 1.7.0 -b test
```

**Comment by phoenix20162016** [comment]
用部署脚本进行部署 https://github.com/primihub/primihub-deploy.git
![image](https://github.com/primihub/primihub/assets/18574396/0da02733-ea75-4042-b065-ac8f0f18cd1d)
这个是1.7.0的image id

**Comment by phoenix20162016** [comment]
@JcobCN 你的问题解决了吗
