### ISSUE TITLE
使用组件问题

### ISSUE THREAD

**Issue by mtl802** [primihub/primihub#760]
我设置组件为【选择数据】-【缺失值填充】-【数据对齐】-【模型选择】，其中选择的数据具有缺失值，中间数据的产生有【缺失值填充】和【数据对齐】组件。查看【缺失值填充】中间数据会显示缺失值已经填充，但是经过这个组件之后的【数据对齐】产生的中间数据却还是拥有缺失值的数据。导致模型训练会报“ValueError: Input contains NaN. ”的错误
![b0d20197c7d39aa7b59a57a7456296a](https://github.com/primihub/primihub/assets/20579710/ef4128a7-bc67-4d7a-a2ad-f7bc3851b17f)
如果先对齐再填充，会报错“缺失值填充错误:null”
![2ea9cfc7869d71805cdcc642a9f1fe8](https://github.com/primihub/primihub/assets/20579710/97a8834b-3cbd-48bf-8e10-38fe623bc9d2)

**Comment by phoenix20162016** [comment]
辛苦把参与计算的节点的执行日志收集，我们最下分析

**Comment by mtl802** [comment]
[日志记录.zip](https://github.com/primihub/primihub/files/14431650/default.zip)
日志记录如上

**Comment by phoenix20162016** [comment]
develop已修复此问题，涉及Primihub-node和Primihub-platform的重新部署，可以自己部署或者等下次release的版本

**Comment by mtl802** [comment]
> develop已修复此问题，涉及Primihub-node和Primihub-platform的重新部署，可以自己部署或者等下次release的版本

好的，麻烦了，能稍微解释一下原因吗

**Comment by phoenix20162016** [comment]
1）先做缺失值填充，这个之前的逻辑会将对齐使用的id列从原数据中删除，导致后续数据对齐部分无效
2）先做数据对齐，这个在管理平台处理缺失值组件时确实是没有将新生成的数据集往下传递

**Comment by mtl802** [comment]
> 1）先做缺失值填充，这个之前的逻辑会将对齐使用的id列从原数据中删除，导致后续数据对齐部分无效 2）先做数据对齐，这个在管理平台处理缺失值组件时确实是没有将新生成的数据集往下传递

关于先对齐在填充这个问题，我从node日志中查看的时候是有Register dataset设置，并且data set的值是改变的，是什么导致数据集没有传递呢

**Comment by phoenix20162016** [comment]
任务配置是由管理平台生成的，之前的版本在新的组件中没有使用新生成的dataset
