### ISSUE TITLE
添加节点提示报错，原因是share/shareData/verifyGateway 这个接口的uniqueIdentification和 value是不匹配导致

### ISSUE THREAD

**Issue by freezehe** [primihub/primihub#763]
Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the past issues](https://github.com/primihub/primihub/issues).

**Describe the bug**

发现可能是你们的一个bug，添加节点的时候调用了share/shareData/verifyGateway?ignore=ignore 这个接口，发现uniqueIdentification和 value是匹配不上导致的，uniqueIdentification的字符串的值前面多了这些字符串：'uniqueIdentification'
<img width="680" alt="6b5680b5f3163f216b86eb507117c74" src="https://github.com/primihub/primihub/assets/11324122/294d8b23-5b42-4f58-9d5f-9125b2b81661">
<img width="958" alt="6752353998278bc3bd14671ebc550a4" src="https://github.com/primihub/primihub/assets/11324122/8dfd7fca-c4e0-4912-89a9-88fd864d1172">

**Steps/Code to Reproduce**

**Expected & actual behavior**

**Nodes log output**

```
node0
```

```
node1
```

```
node2
```

**Enviroment**

- OS: [e.g. macOS, Windows, CentOS, Ubuntu]
- Arch: [e.g. x86_64, armd64, arm64]
- Deployment: [e.g. docker, online, build from source]
- PrimiHub version: e.g. 1.6.8
- Python version: e.g. 3.8.10

**Additional context**

**Comment by rk2b-fenghaolun** [comment]
bug 已经修复了
