### ISSUE TITLE
ubuntu arrch64在部署时,bash deploy.sh拉取mysql失败，no matching ...

### ISSUE THREAD

**Issue by beijiewuhu** [primihub/primihub#764]
![Uploading 屏幕截图 2024-03-10 112330.png…]()

no matching manifest  for linux/arm64/v8 in the manifest list entries

**Comment by phoenix20162016** [comment]
请重新上传下错误信息

**Comment by beijiewuhu** [comment]
[1.pdf](https://github.com/primihub/primihub/files/14693805/1.pdf)

**Comment by beijiewuhu** [comment]
![1](https://github.com/primihub/primihub/assets/161613375/7c4a493e-8426-4869-8780-465432e81956)

**Comment by beijiewuhu** [comment]
它在pulling from library/mysql之后显示
no matching manifest for linux/arm64/v8 in the  manifest list entries

**Comment by phoenix20162016** [comment]
https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8 这个解决方法应该会对你有帮助

**Comment by beijiewuhu** [comment]
![yaml文件](https://github.com/primihub/primihub/assets/161613375/32e94dac-e9cc-4965-85cd-5c66e85f7d18)

**Comment by beijiewuhu** [comment]
![mysql unhealthy](https://github.com/primihub/primihub/assets/161613375/03b7645c-6e47-43ff-841c-121ac418c16e)

学习了您给的解决方法之后，试了它的几个方法之后还是会出现no matching manefest for linux/arm64/v8的问题

**Comment by beijiewuhu** [comment]
![no matching](https://github.com/primihub/primihub/assets/161613375/594f19f2-ff91-434c-bd93-b953d2a202ff)

**Comment by phoenix20162016** [comment]
操作系统以及硬件信息提供下

**Comment by beijiewuhu** [comment]
![屏幕截图 2024-03-25 125813](https://github.com/primihub/primihub/assets/161613375/ab687653-def6-44d2-ad22-98c810f42f50)
![屏幕截图 2024-03-25 130207](https://github.com/primihub/primihub/assets/161613375/81410287-4c31-49d8-8e4f-c5d663338acf)

**Comment by beijiewuhu** [comment]
![屏幕截图 2024-03-25 130219](https://github.com/primihub/primihub/assets/161613375/13080172-0af3-4b9d-a269-a60abea73ba1)
![屏幕截图 2024-03-25 130244](https://github.com/primihub/primihub/assets/161613375/d5fdc208-804b-4e21-9344-69efec3889e6)

**Comment by phoenix20162016** [comment]
镜像应该是不支持aarch64平台的，如果是docker体验的话，建议在x86_64环境中，在aarch64环境中可以用primihub源码编译

**Comment by beijiewuhu** [comment]
请问在本地下载arm64版本的mysql，可以修改yaml文件替换里面的mysql来部署primihub吗？







Krito
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "primihub/primihub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月26日(星期二) 上午10:07
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [primihub/primihub] ubuntu arrch64在部署时,bash deploy.sh拉取mysql失败，no matching ... (Issue #764)





 
镜像应该是不支持aarch64平台的，如果是docker体验的话，建议在x86_64环境中，在aarch64环境中可以用primihub源码编译

**Comment by beijiewuhu** [comment]
![QQMail_1712101977134](https://github.com/primihub/primihub/assets/161613375/1f41e0b9-d5bf-46ee-b183-6ee1829cbde3)
![QQMail_1712101979689](https://github.com/primihub/primihub/assets/161613375/dbc92487-2de7-4fe7-ac74-34bdd8e1c003)

**Comment by beijiewuhu** [comment]
请问在本地下载arm64版本的mysql，可以修改yaml文件替换里面的mysql来部署primihub吗？

**Comment by beijiewuhu** [comment]
这是mysql容器的日志





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月26日(周二) 上午10:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [primihub/primihub] ubuntu arrch64在部署时,bash deploy.sh拉取mysql失败，no matching ... (Issue #764)




 
镜像应该是不支持aarch64平台的，如果是docker体验的话，建议在x86_64环境中，在aarch64环境中可以用primihub源码编译

**Comment by phoenix20162016** [comment]
基于镜像部署在aarch64平台是不支持的，不仅仅mysql，其他的docker镜像都是基于x86生成的
