### ISSUE TITLE
各类模型训练完之后模型文件如何查看

### ISSUE THREAD

**Issue by solio** [primihub/primihub#766]
例如，在线体验平台这个模型文件
[Uploading modelFileName.host…]()

**Comment by phoenix20162016** [comment]
现在只能查看模型训练时基于当前数据集生成的指标参数，对于训练好的模型的详细信息暂时在平台端还没有展示

**Comment by solio** [comment]
@phoenix20162016 那我要如何应用这个模型呢，比如用模型做回归和分类

**Comment by phoenix20162016** [comment]
![image](https://github.com/primihub/primihub/assets/18574396/2f3f056b-72cf-4e67-bc37-0042a2cbcda5)
使用平台上提供的推理服务来调用模型进行预测
