### ISSUE TITLE
1. Data_File 属性和TestData属性的含义是什么。3个参与方计算最大值时，各方分别发送各自资源test_party_0 test_party_1 test_party_2，为什么程序还需要同时读取mpc_test.csv和train_party_0.csv train_party_1.csv train_party_2.csv文件？2. 怎么查看 ./primihub-cli运行的结果文件？是data/result/mpc_max_party_0.csv 和data/result/mpc_max_party_1.csv data/result/mpc_max_party_2.csv 三个参与方对应的文件均是最后计算的最大值 吗？

### ISSUE THREAD

**Issue by Freshcpp** [primihub/primihub#769]
1. 执行 ./primihub-cli --task_config_file="example/mpc_statistics_max_task_conf.json"  
  "PARTY1": {
      "Data_File": "mpc_statistics_1",
      "TestData" : "test_party_1"
    }
读取mpc_test.csv的日志
I20240415 17:51:34.825377 87619 model.cc:119] dataset_access_info: {"data_path":"data/mpc_test.csv","schema":"","type":"CSV"}
I20240415 17:51:34.825421 87619 grpc_impl.cc:35] GrpcDatasetMetaService::PutMeta: {"access_meta":"{\"data_path\":\"data/mpc_test.csv\",\"schema\":\"\",\"type\":\"CSV\"}","data_type":0,"data_url":"node0:127.0.0.1:50050:0::data/mpc_test.csv","description":"mpc_statistics_0","driver_type":"CSV","id":"mpc_statistics_0","schema":"[{\"x_0\":12},{\"x_1\":12},{\"x_2\":12},{\"x_3\":12},{\"x_4\":12},{\"x_5\":12},{\"x_6\":12},{\"x_7\":12},{\"x_8\":12},{\"x_9\":12},{\"x_10\":12},{\"x_11\":12},{\"x_12\":12},{\"x_13\":12},{\"x_14\":12},{\"x_15\":12},{\"x_16\":12},{\"x_17\":12},{\"x_18\":12},{\"x_19\":12},{\"x_20\":12},{\"x_21\":12},{\"x_22\":12},{\"x_23\":12},{\"x_24\":12},{\"x_25\":12},{\"x_26\":12},{\"x_27\":12},{\"x_28\":12},{\"x_29\":12},{\"y\":9}]","server_meta":"node0:127.0.0.1:50050:0:","visibility":0}
I20240415 17:51:34.879961 87619 grpc_impl.cc:50] PutMeta to node: [:127.0.0.1:7977:0:] rpc succeeded.
I20240415 17:51:34.880270 87619 service.cc:263] dataset uid: mpc_arithmetic_0 regiseter success
I20240415 17:51:34.880302 87619 csv_driver.cc:623] access_info_ptr schema column size: 0

**Comment by phoenix20162016** [comment]
https://github.com/primihub/primihub/pull/770/files TestData 这个数据集是没有使用的，可以删除

**Comment by phoenix20162016** [comment]
在联合统计中 outputFilePath 定义了统计的结果存放的路径
