### ISSUE TITLE
匿踪查询大数据量，报265异常

### ISSUE THREAD

**Issue by gpt8763** [primihub/primihub#771]
bug描述
匿踪查询100万数据，报265异常。找不到异常的堆栈信息
复现步骤

1.node2 配置mysql数据库公开资源，node1创建匿踪查询任务。任务启动一会儿后，任务运行失败：WEB界面展示错误信息：
运行失败:SERVER:task execute encountes error
CLIENT:task execute encountes error

node1结点错误日志
I20240507 14:56:21.715778 3085 worker.cc:176] RequestId: ee23c313a633469cb4cafc7583d1ac9c Worker start execute task
I20240507 14:56:21.715879 3075 node_impl.cc:498] RequestId: ee23c313a633469cb4cafc7583d1ac9c create worker thread finished
E20240507 14:56:21.802925 3086 pir_task.cc:252] RequestId: ee23c313a633469cb4cafc7583d1ac9c [{"id":7},{"name":13}]
E20240507 14:56:21.803310 3086 pir_task.cc:129] RequestId: ee23c313a633469cb4cafc7583d1ac9c server_key_columns_: 1 server_label_columns_: 2
E20240507 14:59:41.926980 3085 worker.cc:203] RequestId: ee23c313a633469cb4cafc7583d1ac9c ERROR: 265
I20240507 14:59:42.092892 3075 node_impl.cc:523] RequestId: ee23c313a633469cb4cafc7583d1ac9c , receive request for kill task from SCHEDULER
W20240507 14:59:42.092939 3075 node_impl.cc:535] worker for RequestId: ee23c313a633469cb4cafc7583d1ac9c has finished
I20240507 14:59:42.117178 3050 node_impl.cc:523] RequestId: ee23c313a633469cb4cafc7583d1ac9c , receive request for kill task from SCHEDULER
W20240507 14:59:42.117399 3050 node_impl.cc:535] worker for RequestId: ee23c313a633469cb4cafc7583d1ac9c has finished
环境

OS: Linux
Arch: x86_64
部署方式: docker,
PrimiHub版本: 1.7.0

**Comment by phoenix20162016** [comment]
进入docker 看下dmesg -T 信息，看下是否触发了OOM

**Comment by gpt8763** [comment]
[Wed May  8 17:32:24 2024] Out of memory: Kill process 28894 (task_main) score 489 or sacrifice child
dmesg: read kernel buffer failed: Operation not permitte
是内存不足的问题。
