### ISSUE TITLE
docker-compose启动，运行联邦任务报错"ModuleNotFoundError: No module named 'ph_secure_lib'

### ISSUE THREAD

**Issue by boying960701** [primihub/primihub#780]
docker exec -it primihub-node0 bash
root@098d685b40fb:/app# ./primihub-cli --task_config_file="example/FL/logistic_regression/hfl_binclass_plaintext.json"
I20240603 17:15:39.444339    34 [cli.cc:570](http://cli.cc:570/)] use tls: 0
I20240603 17:15:39.445029    34 [cli.cc:580](http://cli.cc:580/)] SDK SubmitTask to: [127.0.0.1:50050](http://127.0.0.1:50050/)
W20240603 17:15:39.451218    34 [cli.cc:208](http://cli.cc:208/)] task_manager is not one of party in this task, ignore....
I20240603 17:15:39.459542    34 [cli.cc:351](http://cli.cc:351/)] Task Request: task { name: "demoTask" params { param_map { key: "component_params" value { var_type: STRING value_string: "{\"common_params\":{\"alpha\":0.0001,\"batch_size\":100,\"global_epoch\":10,\"id\":\"id\",\"label\":\"y\",\"learning_rate\":1.0,\"local_epoch\":1,\"method\":\"Plaintext\",\"model\":\"HFL_logistic_regression\",\"print_metrics\":true,\"process\":\"train\",\"selected_column\":null,\"task_name\":\"HFL_logistic_regression_binclass_plaintext_train\"},\"role_params\":{\"Alice\":{\"data_set\":\"fl_fake_data\",\"metric_path\":\"data/result/server_metrics.json\"},\"Bob\":{\"data_set\":\"binclass_hfl_train_client1\",\"metric_path\":\"data/result/Bob_metrics.json\",\"model_path\":\"data/result/Bob_model.pkl\"},\"Charlie\":{\"data_set\":\"binclass_hfl_train_client2\",\"metric_path\":\"data/result/Charlie_metrics.json\",\"model_path\":\"data/result/Charlie_model.pkl\"}},\"roles\":{\"client\":[\"Bob\",\"Charlie\"],\"server\":\"Alice\"}}" } } } task_info { task_id: "200" job_id: "100" request_id: "4ea2149a-0c88-484e-8b58-a37d3e43ff1c" } party_datasets { key: "Alice" value { data { key: "data_set" value: "fl_fake_data" } } } party_datasets { key: "Bob" value { data { key: "data_set" value: "binclass_hfl_train_client1" } } } party_datasets { key: "Charlie" value { data { key: "data_set" value: "binclass_hfl_train_client2" } } } } 
I20240603 17:15:39.459637    34 [cli.cc:74](http://cli.cc:74/)] no download cfg, ignore...
I20240603 17:15:39.459728    34 [cli.cc:456](http://cli.cc:456/)] SubmitTask: RequestId: 4ea2149a-0c88-484e-8b58-a37d3e43ff1c 
I20240603 17:15:39.536150    34 [cli.cc:380](http://cli.cc:380/)] party count: 3
I20240603 17:15:43.571410    34 [cli.cc:403](http://cli.cc:403/)] party: "Bob" status: FAIL message: "ModuleNotFoundError: No module named 'ph_secure_lib'

At:
  /usr/local/lib/python3.8/dist-packages/primihub/MPC/util.py(1): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
"
I20240603 17:15:43.578011    34 [cli.cc:403](http://cli.cc:403/)] party: "Alice" status: FAIL message: "ModuleNotFoundError: No module named 'ph_secure_lib'

At:
  /usr/local/lib/python3.8/dist-packages/primihub/MPC/util.py(1): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
"
I20240603 17:15:43.578102    34 [cli.cc:403](http://cli.cc:403/)] party: "Charlie" status: FAIL message: "ModuleNotFoundError: No module named 'ph_secure_lib'

At:
  /usr/local/lib/python3.8/dist-packages/primihub/MPC/util.py(1): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
"
I20240603 17:15:43.578135    34 [cli.cc:413](http://cli.cc:413/)] all node has finished
I20240603 17:15:43.578152    34 [cli.cc:415](http://cli.cc:415/)] party name: Alice msg: ModuleNotFoundError: No module named 'ph_secure_lib'

At:
  /usr/local/lib/python3.8/dist-packages/primihub/MPC/util.py(1): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
I20240603 17:15:43.578176    34 [cli.cc:415](http://cli.cc:415/)] party name: Bob msg: ModuleNotFoundError: No module named 'ph_secure_lib'

At:
  /usr/local/lib/python3.8/dist-packages/primihub/MPC/util.py(1): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
I20240603 17:15:43.578227    34 [cli.cc:415](http://cli.cc:415/)] party name: Charlie msg: ModuleNotFoundError: No module named 'ph_secure_lib'

At:
  /usr/local/lib/python3.8/dist-packages/primihub/MPC/util.py(1): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
I20240603 17:15:43.578289    34 [cli.cc:617](http://cli.cc:617/)] SubmitTask time cost(ms): 4118

**Comment by Klein920116** [comment]
我也同样碰到这个问题，按照官方的docker启动文档，运行任务就报错。急！！！！

**Comment by phoenix20162016** [comment]
https://github.com/primihub/primihub-deploy/releases/tag/1.6.11 用这个部署

**Comment by Klein920116** [comment]
> https://github.com/primihub/primihub-deploy/releases/tag/1.6.11 用这个部署

我用的是快速启动，你说的这个是哪种方式？

**Comment by phoenix20162016** [comment]
已修复， X86架构下的服务器按照doc文件操作即可 @boying960701
