### ISSUE TITLE
docker-compose单机部署后docker exec -it primihub-node0 bash进去容器执行./primihub-cli --task_config_file="example/psi_ecdh_task_conf.json"报错

### ISSUE THREAD

**Issue by boying960701** [primihub/primihub#781]
root@9b6694a0814a:/app# ./primihub-cli --task_config_file="example/psi_ecdh_task_conf.json"
I20240604 10:29:00.636606    86 cli.cc:570] use tls: 0
I20240604 10:29:00.637230    86 cli.cc:580] SDK SubmitTask to: 127.0.0.1:50050
I20240604 10:29:00.648198    86 cli.cc:351] Task Request: task { type: PSI_TASK name: "psi_ecdh_task" language: PROTO params { param_map { key: "clientIndex" value { is_array: true value_int32_array { value_int32_array: 0 } } } param_map { key: "outputFullFilename" value { value_string: "data/result/psi_result.csv" } } param_map { key: "psiTag" value { value_int32: 0 } } param_map { key: "psiType" value { value_int32: 0 } } param_map { key: "serverIndex" value { is_array: true value_int32_array { value_int32_array: 0 } } } param_map { key: "server_outputFullFilname" value { value_string: "data/result/server/psi_result.csv" } } param_map { key: "sync_result_to_server" value { value_int32: 1 } } } task_info { task_id: "200" job_id: "100" request_id: "34e7053a-afa1-450f-9028-e37f81bf0e94" } party_datasets { key: "CLIENT" value { data { key: "CLIENT" value: "psi_client_data" } } } party_datasets { key: "SERVER" value { data { key: "SERVER" value: "psi_server_data" } } } } 
I20240604 10:29:00.648267    86 cli.cc:74] no download cfg, ignore...
I20240604 10:29:00.648367    86 cli.cc:456] SubmitTask: RequestId: 34e7053a-afa1-450f-9028-e37f81bf0e94 
E20240604 10:29:00.659304    86 cli.cc:466] party count from reply is: 0
 message info: dispatch task to party failed, detail: Failed to get all dataset's meta, no handler triggered. expected dataset size: 2, but get: 1
E20240604 10:29:00.659758    86 cli.cc:609] SubmitTask failed

**Comment by phoenix20162016** [comment]
https://github.com/primihub/primihub/issues/782 一样的问题
