### ISSUE TITLE
在二进制文件启动bash start.sh,显示meta_service something wrong，tail无法读取数据，查看Log。

### ISSUE THREAD

**Issue by beijiewuhu** [primihub/primihub#792]
![屏幕截图 2024-08-09 144821](https://github.com/user-attachments/assets/6f81b2c4-9a69-48e3-bd60-2d92b5e72c55)
![屏幕截图 2024-07-31 193748](https://github.com/user-attachments/assets/58e319c3-c69e-49a5-a31e-94fc00ccc249)

**Comment by phoenix20162016** [comment]
和你的环境有一定关系，meta服务启动较慢，在规定的时间内没有检测到meta服务提供服务端口正常开启，在这种情况下可以重新执行bash start_service.sh

**Comment by phoenix20162016** [comment]
还有需要查看下你的系统重是否安装了netstat命令，用于检查meta服务是否正常启动
