### ISSUE TITLE
接入自定义数据以及部署PrimiHub 隐私计算平台

### ISSUE THREAD

**Issue by yaoyizhuo** [primihub/primihub#795]
通过二进制文件启动，服务已经正常启动，并可以跑文档中的任务
操作系统为ubuntu20.04
1.通过grpc接口注册数据，发现引入的包目录中没有./bazel-bin/src/primihub/reg-cli

2.docker部署PrimiHub 隐私计算平台
git clone https://github.com/primihub/primihub-deploy.git
此仓库已经删除了嘛？（现在只可以通过编译jar包部署平台服务？）

**Comment by phoenix20162016** [comment]
1.通过grpc接口注册数据，发现引入的包目录中没有./bazel-bin/src/primihub/reg-cli 这个没有发布到release包中，已经和cli合并为一个工具，可以通过源码编译
